"""init

Revision ID: c00cdff2e435
Revises: 
Create Date: 2026-09-06 15:21:20.304170

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'c00cdff2e435'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='书名'),
    sa.Column('author', sa.String(length=255), nullable=False, comment='作者'),
    sa.Column('description', sa.Text(), nullable=True, comment='简介'),
    sa.Column('cover_url', sa.String(length=500), nullable=True, comment='封面地址'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###